language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script: ./tests/run.sh ./tests/cases

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source

    # Create php.ini & sections.ini
    - cp ./tests/config.sample.neon ./tests/config.neon
    - cp ./tests/php-unix.ini ./tests/php.ini
    - cp ./tests/sections.sample.ini ./tests/sections.ini

    # Create Postgre database
    - psql -c 'CREATE DATABASE nextras_orm_test' -U postgres
